// src/lib/Filter.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import type { globalFilter, filterUnion, TableData } from "../types";
  import type { Writable } from "svelte/store";
  import SubFilter from "./SubFilter.svelte";
  import filterIcon from "@fortawesome/fontawesome-free/svgs/solid/filter.svg";
  import Counter from "./Counter.svelte";

  export let dataKey: keyof TableData = "feats";
  export let filterFunction = () => {};
  let collapsed = true;
  const globalFilters: Writable<globalFilter> = getContext("filters");
  console.log($globalFilters, dataKey);
  const filterKeys = Object.keys($globalFilters[dataKey]) as Array<keyof filterUnion>;
</script>

<div class="filter_container {collapsed ? ' collapsed' : ''}">
  <button
    class="filter_button"
    on:click={() => {
      collapsed = !collapsed;
    }}
  >
    <img src={filterIcon} alt="вкл/выкл фильтр" />
  </button>

  <div class="filter_content{collapsed ? ' collapsed' : ''}">
    {#if !collapsed}
    <Counter/>
    {/if}
    {#each filterKeys as key}
      <SubFilter {key} {dataKey} {filterFunction} />
    {/each}
    <slot />
  </div>
</div>

<style lang="scss">
  .filter_container {
    display: flex;

    padding: 1px;
    position: sticky;
    height: 90vh;
    //overflow-y: auto;
    top: 0;

    & > label {
      margin: 0 0.25rem 1rem;
    }
  }
  .filter_content {
    border: 1px solid black;
    border-radius: 10px;
    overflow-y: auto;
  }
  .filter_button {
    height: fit-content;
    position: absolute;
    top: 1.5rem;
    left: calc(-2rem - 1px);
    padding: 0.25rem 0.25rem;
    z-index: 3;
    display:none
    // background-image: var(--background-image);
  }
  img {
    width: 1.5rem;
  }
  @media (max-aspect-ratio:1/1){
    .filter_button{
      display: block;
    }
  }
</style>

// src/components/filter/FilterComponent.vue
<script setup lang="ts">
import { useFilterStore } from "@stores/filter"
import { computed, provide, ref, watch } from "vue";
import { useRoute } from "vue-router";
import SubFilterComponent from "@components/filter/SubFilterComponent.vue"
import type { DataRoutes, FilterKeys, filterProps } from "@types";
const filterStore = useFilterStore()
const route = useRoute()
const openedFilter = ref("")
provide("openedFilter" as keyof FilterKeys[DataRoutes], openedFilter)
watch(route, () => openedFilter.value = "")
const dataType = computed(() => {
    return route.fullPath.includes('favorites') ? route.fullPath.split('/')[2] as DataRoutes : route.path.replace('/', '') as DataRoutes
})
const filterDataComp = computed(() => {
    if (filterStore.isDataFetched) {
        if (import.meta.env.DEV) {
            console.log()
        }
        return Object.entries(filterStore.filterReadyData[dataType.value]) as [keyof FilterKeys[DataRoutes], filterProps][]
    }
    else {
        return []
    }
})
if (!filterStore.isDataFetched) {
    filterStore.fetchData().then(() => {
        if (import.meta.env.DEV)
            console.log()
    })
}
</script>
<template>
    <div class="filter_main">
        <div class="container">
            <SubFilterComponent v-for="[key, subfilt] in filterDataComp" :key="dataType + subfilt.name"
                :subfiltKey="key" />
        </div>
    </div>
</template>
<style scoped lang="scss">
div.filter_main {
    flex-basis: 30%;
    display: flex;
    flex-direction: column;
    padding: 5px;
    flex-shrink: 0;
    border: 1px solid black;
    border-radius: var(--border-radius)
}

.container {
    flex: 1 1 auto;
    height: 0;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    gap: 10px;
}

@media (max-aspect-ratio:1/1) {
    div.filter_main {
        position: absolute;
        flex-basis: 100%;
        width: calc(100% - 4rem);
        height: 100%;
        transition: opacity .5s ease;

        &.hidden {
            flex-basis: 0;
            z-index: -1;
            opacity: 0 // display: none;
        }
    }
}
</style>
